// Generated by CoffeeScript 1.10.0
(function() {
  var Controller;

  Controller = (function() {
    function Controller() {}

    Controller.prototype.bindAddEvent = function(selector) {
      $(selector).click((function(_this) {
        return function() {
          return _this.addObject();
        };
      })(this));
      return this.newObjectInput.keypress((function(_this) {
        return function(e) {
          if (e.keyCode !== 13) {
            return;
          }
          e.preventDefault();
          return _this.addObject();
        };
      })(this));
    };

    return Controller;

  })();

  window.Controller = Controller;

}).call(this);
