// Generated by CoffeeScript 1.10.0
(function() {
  var DynamicForm,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DynamicForm = (function() {
    function DynamicForm() {
      this.setName = bind(this.setName, this);
      $("form").submit(function() {
        return $("[disabled]").prop("disabled", false);
      });
    }

    DynamicForm.prototype.setName = function(selector, arg, collection) {
      $("form").submit(function() {
        var i, input, j, len, ref, results;
        ref = $(selector);
        results = [];
        for (i = j = 0, len = ref.length; j < len; i = ++j) {
          input = ref[i];
          results.push($(input).attr("name", collection ? collection + "[" + i + "]." + arg : arg));
        }
        return results;
      });
      return this;
    };

    return DynamicForm;

  })();

  window.DynamicForm = DynamicForm;

}).call(this);
