// Generated by CoffeeScript 1.10.0
(function() {
  var Updater;

  Updater = (function() {
    function Updater(interval) {
      if (interval == null) {
        interval = 2000;
      }
      this.update();
      setInterval(this.update, interval);
    }

    return Updater;

  })();

  window.Updater = Updater;

}).call(this);
